"""Init

Revision ID: 1c47bd449d83
Revises: 
Create Date: 2023-04-24 12:01:50.473135

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1c47bd449d83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
                    sa.Column('first_name', sa.String(length=64), nullable=False),
                    sa.Column('last_name', sa.String(length=64), nullable=True),
                    sa.Column('email', sa.String(length=64), nullable=False),
                    sa.Column('birthday', sa.Date(), nullable=True),
                    sa.Column('address', sa.String(length=128), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_on', sa.DateTime(), nullable=False),
                    sa.Column('updated_on', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_index(op.f('ix_contacts_first_name'), 'contacts', ['first_name'], unique=False)
    op.create_table('users',
                    sa.Column('username', sa.String(length=50), nullable=True),
                    sa.Column('email', sa.String(length=150), nullable=False),
                    sa.Column('password', sa.String(length=255), nullable=False),
                    sa.Column('refresh_token', sa.String(length=255), nullable=True),
                    sa.Column('avatar', sa.String(length=255), nullable=True),
                    sa.Column('roles', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_on', sa.DateTime(), nullable=False),
                    sa.Column('updated_on', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('phones',
                    sa.Column('contact_id', sa.Integer(), nullable=False),
                    sa.Column('phone_num', sa.String(length=12), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_on', sa.DateTime(), nullable=False),
                    sa.Column('updated_on', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_phones_phone_num'), 'phones', ['phone_num'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phones_phone_num'), table_name='phones')
    op.drop_table('phones')
    op.drop_table('users')
    op.drop_index(op.f('ix_contacts_first_name'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
